spring:
  profiles:
    active: local # 默认激活 local profile
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 6060


#接口密钥
api:
  password: pubNousGiUkMQboJcyxd:xOqTXCPmNqmhUZNxfhVk
  # 可以直接用